### ISSUE TITLE
Custom Layout padding and margin

### ISSUE THREAD

**Issue by henryaugusta** [Tapadoo/Alerter#241]
Hello i just want to ask how to set margin for custom layout, because the original view has a margin that i think uncustomizable, or maybe i missed a words in documentation ?
Thank You

**Comment by kpmmmurphy** [comment]
Hey @henryaugusta! I think this is one for @minibugdev to answer, as he implemented custom layouts!

**Comment by minibugdev** [comment]
Hi @henryaugusta,

You are right, this library isn't support to customize custom layout margin because of Alerter inflated [alerter_alert_view.xml](https://github.com/Tapadoo/Alerter/blob/master/alerter/src/main/res/layout/alerter_alert_view.xml) to alert view layout which compose with _parent container, content container, button container_.

For custom layout, it was inflated to content container with id `vAlertContentContainer` which inside parent container with id `llAlertBackground`. Unfortunately, the parent have the padding so that why it don't support to customize the margin/padding.

**Comment by henryaugusta** [comment]
Thanks in advance @minibugdev @kpmmmurphy , really appreciate for the suggested solution 👍
